server:
  port: 8085
spring:
  application:
    name: Customers
  datasource:
    url: postgresql://dpg-d36olvj3fgac738vfp5g-a.oregon-postgres.render.com:5432/Customers2
    username: customer2_user
    password: o0mbbfpKclekUFg1PBzFeqEktGP8FiZI
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      eureka:
  instance:
    hostname: localhost
