server:
  port: 8085
spring:
  application:
    name: Customers
  datasource:
    url: postgresql://dpg-d36o5vbipnbc739cjto0-a.oregon-postgres.render.com:5432/Customers
    username: customers_lzzq_user
    password: RmDe7AADM3z76qn7EsoZyfr7MhBsyom2
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      eureka:
  instance:
    hostname: localhost
